version: '2'
services:
  quotes:
    build:
      context: ./QuoteService
      dockerfile: app.dockerfile
    image: ralfx22/sme-quotes:latest
  api:
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    image: ralfx22/sme-api:latest
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./FrontendApplication
      dockerfile: app.dockerfile
    image: ralfx22/sme-frontend:latest
    ports:
      - "8080:80"
    