
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "quotes-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "rbprj-100535"
  location                      = "europe-west1"
  service_name                  = "quotes-service-b8fa"
  containers                    = [{"container_image" = "ralfx22/sme-quotes:v2", "container_name" = "service-container", "ports" = {"container_port" = 5000}}]
  gpu_zonal_redundancy_disabled = false
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_ONLY"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "my-redis-vpc-network"
      subnetwork = "europe-west1-subnet-01"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-rbprj-100535, module.project-services-billing-project]
}
module "api-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "rbprj-100535"
  location                      = "europe-west1"
  service_name                  = "api-service-b8fa"
  containers                    = [{"ports" = {"name" = "http1", "container_port" = 3000}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}, "container_image" = "ralfx22/sme-api:v2_gcp", "container_name" = "service-container", "env_vars" = {"quotes_service_SERVICE_ENDPOINT" = module.quotes-service.service_uri}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_ONLY"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "my-redis-vpc-network"
      subnetwork = "europe-west1-subnet-01"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-rbprj-100535, module.project-services-billing-project]
}
module "frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "rbprj-100535"
  location                      = "europe-west1"
  service_name                  = "frontend-service-b8fa"
  containers                    = [{"ports" = {"name" = "http1", "container_port" = 80}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}, "container_image" = "ralfx22/sme-frontend:v2_gcp_1", "container_name" = "service-container", "env_vars" = {"api_service_SERVICE_ENDPOINT" = module.api-service.service_uri}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "my-redis-vpc-network"
      subnetwork = "europe-west1-subnet-01"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-rbprj-100535, module.project-services-billing-project]
}
module "global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "frontend-lb-backend-b8fa"
  project_id = "rbprj-100535"
  serverless_neg_backends = [{
    region          = module.frontend-service.location
    service_name    = module.frontend-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  depends_on = [module.project-services-rbprj-100535, module.project-services-billing-project]
}
module "global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = "frontend-lb-frontend-b8fa"
  project_id    = "rbprj-100535"
  url_map_input = module.global-lb-backend.backend_service_info
  depends_on    = [module.project-services-rbprj-100535, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = "rbprj-100535"
  location       = "global"
  service_uris   = concat([module.quotes-service.apphub_service_uri], [module.api-service.apphub_service_uri], [module.frontend-service.apphub_service_uri], module.global-lb-backend.apphub_service_uri, module.global-lb-frontend.apphub_service_uri)
  application_id = "sme"
}
module "project-services-rbprj-100535" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "rbprj-100535"
  disable_services_on_destroy = false
  activate_apis               = ["certificatemanager.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "run.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "rbprj-100535"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "certificatemanager.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "run.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
