apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
        - name: quote-service
          image: ralfx22/sme-quotes
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  selector:
    app: quote-service
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ralfx22/sme-api
          ports:
            - containerPort: 3000
          env:
            - name: QUOTES_API
              value: "http://quote-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ralfx22/sme-frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  # key/value hints consumed by the AWS Load Balancer Controller to configure the ALB
  annotations:
	# Legacy way to select the controller (is optional)
    kubernetes.io/ingress.class: alb
    # Determines whether the ALB is public or private
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Controls what the ALB targets, IP targets pod IPs directly
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP"}]'
spec:
  # Modern way to select the controller
  ingressClassName: alb
  rules:
    - http:
        paths:
	        # URL path to match
          - path: /
            # Prefix means: match / and anything starting with /
            pathType: Prefix
            backend:
			        # The Kubernetes Service to route to
              service:
                name: frontend
                port:
                  number: 80
